site_name: juanpml.com
site_author: Juan Pablo Mesa Lopez
site_description: >-
  Applied AI Consulting, ML, LLMs, RAG, and more.

repo_name: blog
repo_url: https://github.com/mesax1/blog/
site_url: https://juanpml.com/
copyright: Copyright &copy; 2024 Juan Pablo Mesa Lopez
theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: phthalo-green
      primary: "#008E45"
      accent: teal 
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: "#008E45"
      accent: teal
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: dark-blue
      accent: teal

  default_scheme: phthalo-green

  custom_dir: docs/stylesheets

extra_css:
  - stylesheets/extra.css

nav:
  - Home: 
    - Introductions: 'index.md'
    - AI Consulting Services: "services.md"
    - RAG Resources: "rag_resources.md"
    - Blog: "https://blog.juanpml.com"
  - Services:
    - AI Consulting Services: "services.md"
  - Writing: "writing/index.md"

plugins:
  - social
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
      prebuild_index: true
  - blog:
      enabled: true
      blog_dir: writing
      blog_toc: true
      post_dir: writing/posts
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      authors_file: "{blog}/.authors.yml"
      draft: false
      draft_on_serve: false
      exclude_drafts: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mesax1
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/juanpml_
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/juan-pablo-mesa-lopez-1633b8148/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/mesax1"  target="_blank" rel="noopener">Juan Pablo Mesa Lopez</a>

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
